#! /bin/sh

#
# This file is licensed under the MIT No Attribution license.
#

#-----------------------------------------------------------------------
# Set up initial error handling
#-----------------------------------------------------------------------

set -e -u || exit

#-----------------------------------------------------------------------
# Set up Qsh
#-----------------------------------------------------------------------
#
# This section was generated using Qsh.
# See <https://github.com/quinngrier/qsh>.
# Qsh is licensed under the MIT No Attribution license.
#

qsh_barf() {

  case $# in (0)
    set "Unknown error"
  esac

  qsh_barf_message="$0: Error:"
  for qsh_barf_text; do
    qsh_barf_message="$qsh_barf_message $qsh_barf_text"
  done
  qsh_barf_message=$qsh_barf_message.

  printf '%s\n' "$qsh_barf_message" >&2

  exit "${qsh_exit_status-1}"

}

qsh_quote() {

  case ${QSH_NDEBUG+1} in ("")
    case $# in (0)
      qsh_barf "qsh_quote:" \
        "At least one argument must be given" \
      ;
    esac
  esac

  qsh_quote_dst=$1
  shift

  case ${QSH_NDEBUG+1} in ("")
    case $qsh_quote_dst in ("" | *[!0-9A-Z_a-z]* | [0-9]*)
      qsh_barf "qsh_quote:" \
        "Invalid <&dst>: \"$qsh_quote_dst\"" \
      ;
    esac
  esac

  qsh_quote_v=

  for qsh_quote_x; do

    case $qsh_quote_v in ("")
      qsh_quote_v=\'
    ;; (*)
      qsh_quote_v="$qsh_quote_v '"
    esac

    while :; do
      case $qsh_quote_x in (*\'*)
        qsh_quote_v=$qsh_quote_v${qsh_quote_x%%\'*}"'\\''"
        qsh_quote_x=${qsh_quote_x#*\'}
      ;; (*)
        qsh_quote_v=$qsh_quote_v$qsh_quote_x\'
        break
      esac
    done

  done

  eval "$qsh_quote_dst=\$qsh_quote_v"

}

#-----------------------------------------------------------------------

unset IFS

nl='
'

parse_options=1

funcs=

while :; do

  case $# in (0)
    break
  esac

  case $parse_options in (1)
    case $1 in (--)
      parse_options=0
      shift
      continue

    ;; (--*)
      x=${1%%=*}
      qsh_barf "Unknown option: $x"

    ;; (-?*)
      x=$(printf '%.2s' "$1")
      case $x in (-)
        x="-$nl"
      esac
      qsh_barf "Unknown option: $x"

    esac
  esac

  qsh_quote x "$1"
  funcs="$funcs $x"

  shift

done

eval set -- "$funcs"

case ${QSH_SRC+x} in (?*)
  src=$QSH_SRC/x
;; (*)
  src=$0
esac
case $src in (/* | [!-]*/*)
  :
;; (*)
  src=./$src
esac
src=${src%/*}/src

hold=
seen_once=
seen_twice=

cat <<'EOF'
#-----------------------------------------------------------------------
# Set up Qsh
#-----------------------------------------------------------------------
#
# This section was generated using Qsh.
# See <https://github.com/quinngrier/qsh>.
# Qsh is licensed under the MIT No Attribution license.
#
EOF

while :; do

  case $# in (0)
    break
  esac

  func=$1
  shift

  case $func in (qsh_*)
    case $func in (*[!0-9A-Z_a-z]*)
      interpret=file
    ;; (*)
      interpret=explicit
    esac
  ;; (:qsh_*)
    func=${func#:}
    case $func in (*[!0-9A-Z_a-z]*)
      func=:$func
      interpret=file
    ;; (*)
      interpret=implicit
    esac
  ;; (*)
    interpret=file
  esac

  case $interpret in (explicit | implicit)

    case $seen_twice in (*" $func "*)
      continue
    esac

    file=$src/$func.sh

    case $seen_once in (*" $func "*)
      # TODO: If --release is given, omit QSH_NDEBUG blocks.
      #       Blocks like this: case ${QSH_NDEBUG+1} in ("")
      awk -- '
        {
          if ($0 ~ /^$/) {
            past_copyright_notice = 1;
          }
          if (past_copyright_notice) {
            print $0;
          }
        }
      ' "$file"
      seen_twice="$seen_twice $func "
      continue
    esac

    test -f "$file" && :
    s=$?
    case $s in (0)
      :
    ;; (1)
      case $interpret in (explicit)
        qsh_barf "Unknown function: $func"
      ;; (implicit)
        seen_twice="$seen_twice $func "
        continue
      esac
    ;; (*)
      exit $s
    esac

    set -- "$file" "$@"
    seen_once="$seen_once $func "
    hold=$func

  ;; (file)

    # TODO: If --release is given, omit QSH_NDEBUG blocks when scanning.
    #       Blocks like this: case ${QSH_NDEBUG+1} in ("")

    script='
      BEGIN {
        if (hold) {
          seen[hold] = 1;
        }
      }
      {
        while ((i = match($0, /qsh_[0-9A-Z_a-z]/)) > 0) {
          $0 = substr($0, i);
          i = match($0, /[^0-9A-Z_a-z]/);
          if (i > 0) {
            x = substr($0, 1, i - 1);
            $0 = substr($0, i);
          } else {
            x = $0;
            $0 = "";
          }
          if (!seen[x]) {
            if (hold) {
              print ":" x;
            } else {
              print x;
            }
            seen[x] = 1;
          }
        }
      }
    '

    case $func in (-)
      deps=$(awk -v hold=$hold -- "$script")
    ;; (*)
      deps=$(awk -v hold=$hold -- "$script" "$func")
    esac

    set -- $deps $hold "$@"
    hold=

  esac

done
