//
// The authors of this file have waived all copyright and
// related or neighboring rights to the extent permitted by
// law as described by the CC0 1.0 Universal Public Domain
// Dedication. You should have received a copy of the full
// dedication along with this file, typically as a file
// named <CC0-1.0.txt>. If not, it may be available at
// <https://creativecommons.org/publicdomain/zero/1.0/>.
//

= Qsh

Qsh is a shell scripting library.

The library supports any POSIX-compatible shell and environment down to
the
link:https://publications.opengroup.org/c43x[UNIX 95]
specification.

The library consists of the functions in the `src` directory.
Each function has its own file.
Each function also has its own file in the `doc` directory.
Some functions may depend on others.

The library reserves all identifiers that start with `qsh_` or `QSH_`.

Unless otherwise noted, all library functions are fail-fast and require
you to use `set -e`.
You also shouldn't call them in any context where `set -e` is suspended,
such as in an `if` condition or on the left side of an `&&` or `||`
operator.

Unless otherwise noted, all library functions support
`set -u`,
`set -o pipefail`,
and `shopt -s inherit_errexit`.

== Usage

Clone this repository and run the `./qsh` script to generate code to
copy into your own script.
You can specify the Qsh functions you want, or files to scan for Qsh
functions.
Scanning just looks for Qsh function names anywhere in the file.
The script will output the specified Qsh functions along with any other
Qsh functions needed as dependencies.

For example:

* `./qsh qsh_barf` will output the `qsh_barf` function.

* `./qsh foo.sh` will scan `foo.sh` for qsh functions and output them.

* `./qsh qsh_barf foo.sh` will combine the previous two examples.

== Documentation

link:doc/qsh_barf.adoc[`qsh_barf`]
link:doc/qsh_bug.adoc[`qsh_bug`]
link:doc/qsh_warn.adoc[`qsh_warn`]

//
