//
// The authors of this file have waived all copyright and
// related or neighboring rights to the extent permitted by
// law as described by the CC0 1.0 Universal Public Domain
// Dedication. You should have received a copy of the full
// dedication along with this file, typically as a file
// named <CC0-1.0.txt>. If not, it may be available at
// <https://creativecommons.org/publicdomain/zero/1.0/>.
//

= Qsh

Qsh is a shell scripting library.

The library supports any POSIX-compatible shell and environment down to
the
link:https://publications.opengroup.org/c43x[UNIX 95]
specification.

The library consists of the functions in the `src` directory, with each
function having its own implementation file.
Each function also has its own documentation file in the `doc`
directory.
Some functions depend on others, forming a dependency graph, but there
are no external dependencies other than POSIX.

The library reserves all identifiers that start with `qsh_` or `QSH_`.

Unless otherwise noted, all library functions are fail-fast and require
you to use `set -e`.
You also shouldn't call them in any context where `set -e` is suspended,
such as in an `if` condition or on the left side of an `&&` or `||`
operator.

Unless otherwise noted, all library functions support
`set -u`,
`set -o pipefail`,
and `shopt -s inherit_errexit`.

== Usage

Clone this repository and run the `./qsh` script to generate code to
copy into your own script.
You can specify the Qsh functions you want, or files to scan for Qsh
functions.
Scanning just looks for Qsh function names anywhere in the file.
The script will output the specified Qsh functions along with any other
Qsh functions needed as dependencies.

For example:

* `./qsh qsh_parse_option` will output the `qsh_parse_option` function
and any other Qsh functions it needs as dependencies.

* `./qsh foo.sh` will scan `foo.sh` for Qsh functions and output them
and any other Qsh functions they need as dependencies.

* `./qsh qsh_parse_option foo.sh` will combine the previous two
examples.

== Documentation

link:doc/qsh_barf.adoc[`qsh_barf`]
link:doc/qsh_bug.adoc[`qsh_bug`]
link:doc/qsh_csf.adoc[`qsh_csf`]
link:doc/qsh_parse_option.adoc[`qsh_parse_option`]
link:doc/qsh_unknown_operand.adoc[`qsh_unknown_operand`]
link:doc/qsh_unknown_option.adoc[`qsh_unknown_option`]
link:doc/qsh_warn.adoc[`qsh_warn`]

//
